load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "hello-window",
    srcs = ["main.cpp"],
    deps = [
        "@my-glad//:glad",
        "@my-glfw//:glfw",
    ],
)

cc_binary(
    name = "hello-world",
    srcs = ["hello_world.cpp"],
)
